SELECT  a.AUTHOR_ID,
        a.AUTHOR_NAME,
        b.CATEGORY,
        SUM(bs.SALES * b.PRICE) AS 'TOTAL_SALES'
FROM    BOOK b
JOIN    AUTHOR a
ON      b.AUTHOR_ID = a.AUTHOR_ID
JOIN    BOOK_SALES bs
ON      b.BOOK_ID = bs.BOOK_ID
WHERE   bs.SALES_DATE >= '2022-01-01'
AND     bs.SALES_DATE < '2022-02-01'
GROUP BY a.AUTHOR_ID, a.AUTHOR_NAME, b.CATEGORY
ORDER BY 1, 3 DESC;