SELECT  DISTINCT(c.CART_ID)
FROM    CART_PRODUCTS c
WHERE   EXISTS(SELECT NAME FROM CART_PRODUCTS WHERE c.CART_ID = CART_ID AND NAME = 'Yogurt')
AND     EXISTS(SELECT NAME FROM CART_PRODUCTS WHERE c.CART_ID = CART_ID AND NAME = 'Milk')
ORDER BY 1;