SELECT  i.ITEM_ID,
        i.ITEM_NAME,
        i.RARITY
FROM    ITEM_TREE t
LEFT JOIN   ITEM_TREE t2 ON t.ITEM_ID = t2.PARENT_ITEM_ID
LEFT JOIN   ITEM_INFO i ON t.ITEM_ID = i.ITEM_ID
WHERE   t2.ITEM_ID IS NULL
ORDER BY 1 DESC;