SELECT  p.PRODUCT_CODE,
        SUM(o.SALES_AMOUNT) * p.PRICE as 'SALES'
FROM    PRODUCT p
INNER JOIN  OFFLINE_SALE o
ON      p.PRODUCT_ID = o.PRODUCT_ID
GROUP BY o.PRODUCT_ID
ORDER BY SUM(o.SALES_AMOUNT) * p.PRICE DESC, PRODUCT_CODE;