SELECT  YEAR(os.SALES_DATE) AS 'YEAR',
        MONTH(os.SALES_DATE) AS 'MONTH',
        i.GENDER,
        COUNT(DISTINCT(os.USER_ID)) AS 'USERS'
FROM    ONLINE_SALE os
JOIN    USER_INFO i
ON      os.USER_ID = i.USER_ID
WHERE   GENDER IS NOT NULL
GROUP BY 1, 2, 3
ORDER BY 1, 2, 3;

# SELECT  *
# FROM    ONLINE_SALE
# ORDER BY USER_ID;

# SELECT  *
# FROM    USER_INFO;