WITH TBL AS (
    SELECT  CAST(REPLACE(DURATION_TYPE, '일 이상', '') AS UNSIGNED) AS 'NUM_DURATOIN_TYPE',
            DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE CAR_TYPE = '트럭'
)

SELECT  h.HISTORY_ID,
        ROUND((DATEDIFF(h.END_DATE, h.START_DATE) + 1) * c.DAILY_FEE * (1 - IFNULL(t.DISCOUNT_RATE, 0) / 100), 0) AS 'FEE'
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY h
LEFT JOIN CAR_RENTAL_COMPANY_CAR c
ON h.CAR_ID = c.CAR_ID
LEFT JOIN TBL t
ON t.NUM_DURATOIN_TYPE = 
CASE
    WHEN DATEDIFF(h.END_DATE, h.START_DATE) + 1 >= 90 THEN 90
    WHEN DATEDIFF(h.END_DATE, h.START_DATE) + 1 >= 30 THEN 30
    WHEN DATEDIFF(h.END_DATE, h.START_DATE) + 1 >= 7 THEN 7
END
WHERE h.CAR_ID IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_CAR
    WHERE CAR_TYPE = '트럭'
)
ORDER BY 2 DESC, 1 DESC;