SELECT  f.FLAVOR
FROM    FIRST_HALF f
RIGHT JOIN    JULY j
ON  f.SHIPMENT_ID = j.SHIPMENT_ID
GROUP BY j.FLAVOR
HAVING SUM(f.TOTAL_ORDER) + SUM(j.TOTAL_ORDER)
ORDER BY SUM(f.TOTAL_ORDER) + SUM(j.TOTAL_ORDER) DESC
LIMIT 3;