WITH RECURSIVE HOURS AS (
    SELECT 0 AS H
    UNION ALL
    SELECT H + 1 FROM HOURS WHERE H < 23
)

SELECT  h.H AS 'HOUR',
        COUNT(o.DATETIME)
FROM    HOURS h
LEFT JOIN    ANIMAL_OUTS o
ON  h.H = HOUR(o.DATETIME)
GROUP BY 1
ORDER BY 1;