SELECT DISTINCT b.CAR_ID
FROM    CAR_RENTAL_COMPANY_CAR a
INNER JOIN  CAR_RENTAL_COMPANY_RENTAL_HISTORY b
ON      a.CAR_ID = b.CAR_ID
WHERE   CAR_TYPE = '세단'
AND     MONTH(START_DATE) = 10
ORDER BY 1 DESC;