SELECT  CONCAT('/home/grep/src/', b.BOARD_ID, '/', f.FILE_ID, FILE_NAME, FILE_EXT) AS 'FILE_PATH'
FROM    
    (
        SELECT  BOARD_ID
        FROM    USED_GOODS_BOARD
        ORDER BY VIEWS DESC
        LIMIT 1
    ) b
INNER JOIN USED_GOODS_FILE f
ON b.BOARD_ID = f.BOARD_ID
ORDER BY f.FILE_ID DESC;