SELECT  a.CATEGORY,
        SUM(b.SALES) as 'TOTAL_SALES'
FROM    BOOK a
INNER JOIN BOOK_SALES b
ON      a.BOOK_ID = b.BOOK_ID
WHERE  b.SALES_DATE >= '2022-01-01' AND b.SALES_DATE < '2022-02-01'
GROUP BY a.CATEGORY
ORDER BY 1;