SELECT  f.CATEGORY,
        f.PRICE AS 'MAX_PRICE',
        f.PRODUCT_NAME
FROM    FOOD_PRODUCT f
WHERE   f.CATEGORY IN ('과자', '국', '김치', '식용유')
AND     f.PRICE = (
    SELECT  MAX(PRICE)
    FROM    FOOD_PRODUCT
    WHERE   CATEGORY = f.CATEGORY
)
ORDER BY 2 DESC;